In [16]:
import numpy as np

In [17]:
x= np.array([1,2,3,4])
print(x, type(x))

[1 2 3 4] <class 'numpy.ndarray'>

In [18]:
%timeit [i**5 for i in range(1,10)]

1.47 μs ± 624 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)

In [19]:
import numpy as np
%timeit np.arange(1,10)**5

2.79 μs ± 438 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)

In [20]:
x.ndim

1

In [21]:
y=np.array([[[12,3,4]]])

In [22]:
print(y,type(y),y.ndim)

[[[12  3  4]]] <class 'numpy.ndarray'> 3

In [23]:
n=lambda: np.array([input("enter the number") for _ in range(1,5)])
yy=n()

In [24]:
yy

array(['1', '2', '2', ''], dtype='<U1')

In [25]:
arr=np.ones((4,7), dtype=bool)
arr

array([[ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True]])

In [26]:
r=np.empty(3)

In [27]:
r

array([ 1.14e-322,  4.94e-324, -0.00e+000])

In [28]:
s=np.arange(2,9,2)

In [29]:
s

array([2, 4, 6, 8])

In [30]:

e=np.linspace(3,7)
e

array([3.        , 3.08163265, 3.16326531, 3.24489796, 3.32653061,
       3.40816327, 3.48979592, 3.57142857, 3.65306122, 3.73469388,
       3.81632653, 3.89795918, 3.97959184, 4.06122449, 4.14285714,
       4.2244898 , 4.30612245, 4.3877551 , 4.46938776, 4.55102041,
       4.63265306, 4.71428571, 4.79591837, 4.87755102, 4.95918367,
       5.04081633, 5.12244898, 5.20408163, 5.28571429, 5.36734694,
       5.44897959, 5.53061224, 5.6122449 , 5.69387755, 5.7755102 ,
       5.85714286, 5.93877551, 6.02040816, 6.10204082, 6.18367347,
       6.26530612, 6.34693878, 6.42857143, 6.51020408, 6.59183673,
       6.67346939, 6.75510204, 6.83673469, 6.91836735, 7.        ])

In [31]:
n=np.arange(1,10)

In [32]:
n

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
x=n.reshape(3,3)

In [34]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
x.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
x.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [38]:
np.eye(3,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [39]:
a=np.random.randint(5,10,2)
print(a)

[6 8]

In [40]:

a=np.arange((1,10))
print(a.dtype)

TypeError: arange: scalar arguments expected instead of a tuple.

In [ ]:
print(a.type())

AttributeError: 'numpy.ndarray' object has no attribute 'type'

In [ ]:
uv add pandas

Note: you may need to restart the kernel to use updated packages.

g:\AI_ML_Project\Agentic_AI_Project\Chat_Bot\.venv\Scripts\python.exe: No module named uv

In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv("F:\ihh new\python\pandas\services.csv")

<>:1: SyntaxWarning: invalid escape sequence '\i'
<>:1: SyntaxWarning: invalid escape sequence '\i'
C:\Users\HP\AppData\Local\Temp\ipykernel_11796\1883221242.py:1: SyntaxWarning: invalid escape sequence '\i'
  df=pd.read_csv("F:\ihh new\python\pandas\services.csv")

In [ ]:
df.head(5)

,id,location_id,program_id,accepted_payments,alternate_name,application_process,audience,description,eligibility,email,...,interpretation_services,keywords,languages,name,required_documents,service_areas,status,wait_time,website,taxonomy_ids
0,1,1,NaN,NaN,NaN,Walk in or apply by phone.,"Older adults age 55 or over, ethnic minorities...",A walk-in center for older adults that provide...,"Age 55 or over for most programs, age 60 or ov...",NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Meal Sites...",NaN,Fair Oaks Adult Activity Center,NaN,Colma,active,No wait.,NaN,NaN
1,2,2,NaN,NaN,NaN,Apply by phone for an appointment.,Residents of San Mateo County age 55 or over,Provides training and job placement to eligibl...,"Age 55 or over, county resident and willing an...",NaN,...,NaN,"EMPLOYMENT/TRAINING SERVICES, Job Development,...",NaN,Second Career Employment Program,NaN,San Mateo County,active,Varies.,NaN,NaN
2,3,3,NaN,NaN,NaN,Phone for information (403-4300 Ext. 4322).,Older adults age 55 or over who can benefit fr...,Offers supportive counseling services to San M...,Resident of San Mateo County age 55 or over,NaN,...,NaN,"Geriatric Counseling, Older Adults, Gay, Lesbi...",NaN,Senior Peer Counseling,NaN,San Mateo County,active,Varies.,NaN,NaN
3,4,4,NaN,NaN,NaN,Apply by phone.,"Parents, children, families with problems of c...",Provides supervised visitation services and a ...,NaN,NaN,...,NaN,"INDIVIDUAL AND FAMILY DEVELOPMENT SERVICES, Gr...",NaN,Family Visitation Center,NaN,San Mateo County,active,No wait.,NaN,NaN
4,5,5,NaN,NaN,NaN,Phone for information.,Low-income working families with children tran...,Provides fixed 8% short term loans to eligible...,Eligibility: Low-income family with legal cust...,NaN,...,NaN,"COMMUNITY SERVICES, Speakers, Automobile Loans",NaN,Economic Self-Sufficiency Program,NaN,San Mateo County,active,NaN,NaN,NaN

In [ ]:
type(df)

pandas.DataFrame

In [ ]:
df.columns

Index(['id', 'location_id', 'program_id', 'accepted_payments',
       'alternate_name', 'application_process', 'audience', 'description',
       'eligibility', 'email', 'fees', 'funding_sources',
       'interpretation_services', 'keywords', 'languages', 'name',
       'required_documents', 'service_areas', 'status', 'wait_time', 'website',
       'taxonomy_ids'],
      dtype='str')

In [ ]:
df["funding_sources"]

0     City, County, Donations, Fees, Fundraising
1                         County, Federal, State
2                      County, Donations, Grants
3                      County, Donations, Grants
4                          County, Grants, State
5                Fees, Fundraising, Grants, Dues
6                        Donations, Fees, Grants
7                              County, Donations
8                                   City, County
9                                           City
10                                          City
11       City, Donations, Federal, Grants, State
12                                          City
13                             Donations, Grants
14                              Donations, Sales
15                       Donations, Fees, Grants
16                                     Donations
17                             Donations, Grants
18                             Donations, Grants
19                                           NaN
20                                           NaN
21                  City, County, Federal, State
22                  City, County, Federal, State
Name: funding_sources, dtype: str

In [ ]:
list(df.columns)

['id',
 'location_id',
 'program_id',
 'accepted_payments',
 'alternate_name',
 'application_process',
 'audience',
 'description',
 'eligibility',
 'email',
 'fees',
 'funding_sources',
 'interpretation_services',
 'keywords',
 'languages',
 'name',
 'required_documents',
 'service_areas',
 'status',
 'wait_time',
 'website',
 'taxonomy_ids']

In [ ]:
df[['languages',
 'name',
 'required_documents']]

,languages,name,required_documents
0,NaN,Fair Oaks Adult Activity Center,NaN
1,NaN,Second Career Employment Program,NaN
2,NaN,Senior Peer Counseling,NaN
3,NaN,Family Visitation Center,NaN
4,NaN,Economic Self-Sufficiency Program,NaN
5,NaN,Little House Recreational Activities,NaN
6,NaN,Rosener House Adult Day Services,NaN
7,NaN,Meals on Wheels - South County,NaN
8,NaN,Fair Oaks Branch,NaN
9,NaN,Main Library,NaN
10,NaN,Schaberg Branch,NaN
11,NaN,Project Read,NaN
12,NaN,Redwood Shores Branch,NaN
13,NaN,Redwood City Corps,NaN
14,NaN,Adult Rehabilitation Center,NaN
15,NaN,Sunnyvale Corps,NaN
16,NaN,South San Francisco Citadel Corps,NaN
17,NaN,Project Smile,NaN
18,NaN,San Mateo Free Medical Clinic,NaN
19,NaN,Service with blank fields,NaN
20,NaN,Service for Admin Test Location,NaN
21,Spanish,Passport Photos,Government-issued picture identification
22,NaN,Example Service Name,NaN

In [ ]:
df.dtypes

id                           int64
location_id                  int64
program_id                 float64
accepted_payments              str
alternate_name                 str
application_process            str
audience                       str
description                    str
eligibility                    str
email                          str
fees                           str
funding_sources                str
interpretation_services        str
keywords                       str
languages                      str
name                           str
required_documents             str
service_areas                  str
status                         str
wait_time                      str
website                        str
taxonomy_ids                   str
dtype: object

In [42]:
df=pd.read_excel("F:\ihh new\python\pandas\LUSID Excel - Setting up your market data (1).xlsx")

<>:1: SyntaxWarning: invalid escape sequence '\i'
<>:1: SyntaxWarning: invalid escape sequence '\i'
C:\Users\HP\AppData\Local\Temp\ipykernel_11796\2753470536.py:1: SyntaxWarning: invalid escape sequence '\i'
  df=pd.read_excel("F:\ihh new\python\pandas\LUSID Excel - Setting up your market data (1).xlsx")

In [43]:
df.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,Datetimes in LUSID,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,This sheet allows you to format datetimes for...,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,If you have any questions please visit our:,NaN,NaN,NaN,NaN,NaN,NaN

In [44]:
df.tail()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
23,NaN,NaN,NaN,NaN,Although the date can still appears without time,2019-04-10 13:30:45.550000,NaN,NaN,NaN,NaN
24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,NaN,NaN,NaN,NaN,Add an hour to your datetime,2019-04-10 14:30:45.550000,NaN,NaN,NaN,NaN
26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,NaN,NaN,NaN,NaN,Subtract a minute from your datetime,2019-04-10 14:29:45.550000,NaN,NaN,NaN,NaN

In [45]:
df.dtypes

Unnamed: 0    float64
Unnamed: 1    float64
Unnamed: 2    float64
Unnamed: 3        str
Unnamed: 4        str
Unnamed: 5     object
Unnamed: 6    float64
Unnamed: 7        str
Unnamed: 8        str
Unnamed: 9        str
dtype: object

In [46]:
df.columns

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9'],
      dtype='str')

In [47]:
list[df.columns]

list[Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9'],
      dtype='str')]

In [48]:
df[['Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3']]

    Unnamed: 1  Unnamed: 2                                         Unnamed: 3
0          NaN         NaN                                                NaN
1          NaN         NaN                                 Datetimes in LUSID
2          NaN         NaN                                                NaN
3          NaN         NaN   This sheet allows you to format datetimes for...
4          NaN         NaN        If you have any questions please visit our:
5          NaN         NaN                                                NaN
6          NaN         NaN                                                NaN
7          NaN         NaN                                                NaN
8          NaN         NaN                                                NaN
9          NaN         NaN                                                NaN
10         NaN         NaN                                                NaN
11         NaN         NaN                                                NaN
12         NaN         NaN                                                NaN
13         NaN         NaN                                                NaN
14         NaN         NaN                                                NaN
15         NaN         NaN                                                NaN
16         NaN         NaN                                                NaN
17         NaN         NaN                                                NaN
18         NaN         NaN                                                NaN
19         NaN         NaN                                                NaN
20         NaN         NaN                                                NaN
21         NaN         NaN                                                NaN
22         NaN         NaN                                                NaN
23         NaN         NaN                                                NaN
24         NaN         NaN                                                NaN
25         NaN         NaN                                                NaN
26         NaN         NaN                                                NaN
27         NaN         NaN                                                NaN